spring.application.name=peliculas-frontend
upload.dir=src/main/resources/static/uploads
server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/peliculasdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=b5ba43e5e4+
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
backend.url=http://localhost:8082
# --- Tamaño máximo de archivo ---
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-part-count=50

# URL del API Gateway
backend.gateway.url=http://localhost:8080
