name: Analisis SonarQube

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonar:
    name: Revisar codigo con SonarQube
    runs-on: self-hosted

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Compilar api-gateway
        working-directory: api-gateway
        run: mvn clean package -DskipTests

      - name: Compilar eureka-server
        working-directory: eureka-server
        run: mvn clean package -DskipTests

      - name: Compilar peliculas-service
        working-directory: peliculas-service
        run: mvn clean package -DskipTests

      - name: Compilar usuarios-service
        working-directory: usuarios-service
        run: mvn clean package -DskipTests

      - name: Analizar codigo con SonarQube
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.projectKey=peliculas \
            -Dsonar.projectName=peliculas \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=api-gateway/src,eureka-server/src,peliculas-service/src,usuarios-service/src,peliculas-frontend \
            -Dsonar.java.binaries=api-gateway/target/classes,eureka-server/target/classes,peliculas-service/target/classes,usuarios-service/target/classes \
            -Dsonar.exclusions=**/target/**,**/src/test/**,**/.git/** \
            -Dsonar.coverage.exclusions=**/model/**/*.java,**/dto/**/*.java